$ErrorActionPreference = 'Stop'

$src = 'C:\Users\user\Downloads\report-db.sql'
$dstDir = 'C:\Users\user\ministry-report-system\server\scripts'
$dst = Join-Path $dstDir 'report-db-fixed.sql'

if (!(Test-Path -LiteralPath $src)) {
  throw "Source file not found: $src"
}

New-Item -ItemType Directory -Force -Path $dstDir | Out-Null

$content = Get-Content -Raw -LiteralPath $src

# Remove original transaction + truncate lines (we'll provide our own safe prelude)
$content = $content -replace '(?m)^\s*BEGIN;\s*$\r?\n?', ''
$content = $content -replace '(?m)^\s*COMMIT;\s*$\r?\n?', ''
$content = $content -replace '(?m)^\s*TRUNCATE\s+TABLE\s+.*\s*$\r?\n?', ''

$prelude = @'
-- Ministry Report System SQL Restore (fixed)
-- Fixes:
-- 1) Creates missing tables used by the backup ("Users", "Reports", "Attachments", "ReportFormTemplates")
-- 2) Uses a safe TRUNCATE after table creation
-- 3) Wraps restore in a single transaction

-- Ensure enum type exists (matches Sequelize naming)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_Users_role') THEN
    CREATE TYPE "enum_Users_role" AS ENUM ('admin', 'leader', 'member');
  END IF;
END $$;

-- Core tables (matching Sequelize defaults)
CREATE TABLE IF NOT EXISTS "Users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fullname" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) NOT NULL UNIQUE,
  "password" VARCHAR(255) NOT NULL,
  "role" "enum_Users_role" NOT NULL DEFAULT 'member',
  "country" VARCHAR(255) NOT NULL,
  "contact" VARCHAR(255),
  "address" VARCHAR(255),
  "profile_image" VARCHAR(255),
  "resetPasswordToken" VARCHAR(255),
  "resetPasswordExpire" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "Reports" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" DATE NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "country" VARCHAR(255) NOT NULL,
  "church" VARCHAR(255) NOT NULL,
  "evangelism_hours" DOUBLE PRECISION DEFAULT 0,
  "people_reached" INTEGER DEFAULT 0,
  "contacts_received" INTEGER DEFAULT 0,
  "bible_study_sessions" INTEGER DEFAULT 0,
  "bible_study_attendants" INTEGER DEFAULT 0,
  "unique_attendants" INTEGER DEFAULT 0,
  "newcomers" INTEGER DEFAULT 0,
  "meditation_time" DOUBLE PRECISION DEFAULT 0,
  "prayer_time" DOUBLE PRECISION DEFAULT 0,
  "morning_service" VARCHAR(255),
  "regular_service" VARCHAR(255),
  "sermons_listened" INTEGER DEFAULT 0,
  "articles_written" INTEGER DEFAULT 0,
  "exercise_time" DOUBLE PRECISION DEFAULT 0,
  "sermon_reflection" TEXT,
  "reflections" TEXT,
  "thanksgiving" TEXT,
  "repentance" TEXT,
  "prayer_requests" TEXT,
  "other_work" TEXT,
  "tomorrow_tasks" TEXT,
  "other_activities" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "user_id" INTEGER,
  CONSTRAINT "Reports_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "Users"("id") ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "Attachments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "file_url" VARCHAR(1024) NOT NULL,
  "file_type" VARCHAR(255),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "report_id" INTEGER,
  CONSTRAINT "Attachments_report_id_fkey" FOREIGN KEY ("report_id") REFERENCES "Reports"("id") ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "ReportFormTemplates" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "definition" JSONB NOT NULL,
  "is_active" BOOLEAN NOT NULL DEFAULT FALSE,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

BEGIN;
TRUNCATE TABLE "Attachments", "Reports", "ReportFormTemplates", "Users" RESTART IDENTITY CASCADE;

'@

$final = $prelude + $content.Trim() + "`r`n`r`nCOMMIT;`r`n"
Set-Content -LiteralPath $dst -Value $final -Encoding utf8

Write-Output "OK: wrote fixed SQL to $dst"
